apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lifetracker
namePrefix: dev-
resources:
  - configmap.yaml
  - secret.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - backend-service.yaml
  - frontend-service.yaml
