apiVersion: v1
kind: Secret
metadata:
  name: remote-ai-ide-secrets
  namespace: lifetracker
  labels:
    app: remote-ai-ide

type: Opaque

stringData:
  AUTH_TOKENS: "clLPw4832audE"
  SSH_HOST_BRAHAMMAR: "brahammar.ddns.net"
  SSH_USER_BRAHAMMAR: "root"
  SSH_PASSWORD_BRAHAMMAR: "coLPw4832ntabO"
  SSH_HOST_ALLPURPOSE: "allpurpose.ddns.net"
  SSH_PORT_ALLPURPOSE: "222"
  SSH_USER_ALLPURPOSE: "truls"
  SSH_PASSWORD_ALLPURPOSE: "grigri08"
